#配置服务器信息
server:
  port: 8080
#配置数据源
spring:
  datasource:
    url: jdbc:mysql://192.168.108.101:3306/task?useUnicode=yes&characterEncoding=UTF-8&useSSL=false
    password: 123456
    username: root
    driver-class-name: com.mysql.jdbc.Driver
#配置mybatis
mybatis-plus:
  mapper-locations: classpath:mapping/*.xml
  type-aliases-package: com.weiliai.task.model
  configuration:
    map-underscore-to-camel-case: true


#配置定时任务线程池大小
schedule:
  pool-size: 4
#打印SQL
logging:
  level: {com.weiliai.task.mapper: debug}


